# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculates the realized dominance relationship matrix
#' 
#' @description Calculates realized dominance relationship matrix.
#'
#' @param X is a (numeric, \eqn{n}{m}) matrix of genotypes with a number of rows identical to the number of SNPs (m) and a number of columns identical to the number of genotyped individuals (n). Values in the matrix are 0 and 2 for homozygous and 1 for heterozygous.
#' 
#' @examples
#' ## Not to run ##
#' 
#' ## DRM(X)
#'
#' ## End(Not run)
#' 
#' @references VanRaden, Paul M. Efficient methods to compute genomic predictions. Journal of dairy science 91.11 (2008): 4414-4423.
#' 
#' @references Su G, Christensen OF, Ostersen T, Henryon M, Lund MS. 2012. Estimating Additive and Non-Additive Genetic Variances and Predicting Genetic Merits Using Genome-Wide Dense Single Nucleotide Polymorphism Markers. PLoS ONE 7(9): e45293. doi:10.1371/journal.pone.0045293
#' 
#' 
#' @useDynLib GDmat
#'
#' @export DRM
DRM <- function(X) {
    .Call('_GDmat_DRM', PACKAGE = 'GDmat', X)
}

#' @title Calculates the realized additive relationship matrix
#' 
#' @description Calculates realized additive (genomic) relationship matrix.
#'
#' @param X is a (numeric, \eqn{n}{m}) matrix of genotypes with a number of rows identical to the number of SNPs (m) and a number of columns identical to the number of genotyped individuals (n). Values in the matrix are 0 and 2 for homozygous and 1 for heterozygous.
#' @param smallValue is a numeric valeu that can be added to the diagonal of the genomic relationship matrix (GRM).
#' 
#' @examples
#' ## Not to run ##
#' 
#' ## GRM(X, smallValue)
#'
#' ## End(Not run)
#' 
#' @references VanRaden, Paul M. Efficient methods to compute genomic predictions. Journal of dairy science 91.11 (2008): 4414-4423.
#' 
#' @references Su G, Christensen OF, Ostersen T, Henryon M, Lund MS. 2012. Estimating Additive and Non-Additive Genetic Variances and Predicting Genetic Merits Using Genome-Wide Dense Single Nucleotide Polymorphism Markers. PLoS ONE 7(9): e45293. doi:10.1371/journal.pone.0045293
#' 
#' 
#' @useDynLib GDmat
#'
#' @export GRM
GRM <- function(X, smallValue) {
    .Call('_GDmat_GRM', PACKAGE = 'GDmat', X, smallValue)
}

