# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DRM <- function(X) {
    .Call('_GDmat_DRM', PACKAGE = 'GDmat', X)
}

GRM <- function(X, smallValue) {
    .Call('_GDmat_GRM', PACKAGE = 'GDmat', X, smallValue)
}

rcpp_makeA <- function(numSire, numDam, AFounder, numFounder, IndivName) {
    .Call('_GDmat_rcpp_makeA', PACKAGE = 'GDmat', numSire, numDam, AFounder, numFounder, IndivName)
}

rcpp_makeA_lowMem <- function(numSire, numDam, AFounder, numFounder, IndivName, numKeep, ainKeep, anOff) {
    .Call('_GDmat_rcpp_makeA_lowMem', PACKAGE = 'GDmat', numSire, numDam, AFounder, numFounder, IndivName, numKeep, ainKeep, anOff)
}

